### ISSUE TITLE
/recordsにトップからアクセスする経路がなくね？

### ISSUE THREAD

**Issue by shizone** [LuckOfWise/daitokaiet#9]
/records/newからbackするしか経路がないんスけど

**Comment by shizone** [comment]
これメニューに入れてええのんかな

**Comment by LuckOfWise** [comment]
newからbackでいいんじゃね？って思ってた。

2013/12/19 razon notifications@github.com

**Comment by shizone** [comment]
画面の存在に気づかない人が結構いそうだなー #俺

**Comment by LuckOfWise** [comment]
そんな馬鹿な。
一回登録したらrecordsに遷移するだろ。

2013/12/19 razon notifications@github.com

**Comment by shizone** [comment]
あー

**Comment by shizone** [comment]
うん、正解な気がする。
敢えて最初に/recordsから見る必要はないな。

**Comment by LuckOfWise** [comment]
なんというか仕事っぽいやりとりｗ

2013/12/19 razon notifications@github.com
